### ISSUE TITLE
Issues before update

### ISSUE THREAD

**Issue by varunn12** [varunn12/Reweyou#8]
Likes Count not increasing-**DONE**
Edit Gallery Activity to share directly from activity for videos, normal image and gif.  -**?? More description**
Posts are not loading after 20. **DONE**
Activity not opening on clicking on edit test (reporting at the top). -**DONE**
Can't see readers of other users (Click not working on readers).-**DONE**
Work to report only text  #reports-**DONE**
Remove CityAdapter from all places and replace it with Message adapter or make CityAdapter same as Message Adapter else app will crash at search, My City etc.
Feed Settings - Followed toast message..and make sure app doesn't crash on fast selection.-**DONE (yet to be optimized)** 
Your profile image is showing when video or gif reported from my profile (Actually your profile pic is showing probably you have hard coded your number)
Video viewing experience is bad. Also can we not make video autoplay in same feed?
No gif compression?
Opening reactions from anywhere other than feed like Search, My City, Location or User Profile - App Crash
Liking post from anywhere other than feed - No Like
App Crash on clicking on reactions from Notifications-**DONE**
Updating What's New
Only headline is shwoing when i reported an story from your profile. No Content - **DONE**

**Comment by apgapg** [comment]
Thanks for reporting the issues in the app. The same would be corrected soon. Thankyou. 

Regards, 
Ayush P Gupta.

**Comment by apgapg** [comment]
Updated and fixed all above bugs and errors
